google.charts.load('current', {'packages':['sankey']});
google.charts.setOnLoadCallback(drawChart);

function drawChart() {
  var data = new google.visualization.DataTable();
  data.addColumn('string', 'From');
  data.addColumn('string', 'To');
  data.addColumn('number', 'Weight');
  data.addRows([

    [ 'Aldan River', 'Lena River', 28.1],
    [ 'Amazon River', 'Atlantic Ocean', 237.267],
    [ 'Amur River', 'Pacific Ocean', 74.516],
    [ 'Anadyr River', 'Bering Sea', 7.4],
    [ 'Angara River', 'Yenisei River', 40.1],
    [ 'Apure River', 'Orinoco River', 5.2569],
    [ 'Arabian Sea', 'Indian Ocean', 45.5754],
    [ 'Araguaia River', 'Tocantins River', 13.8273],
    [ 'Argun / Hailar River', 'Amur River', 6.3],
    [ 'Arkansas River', 'Mississippi River', 16.8002],
    [ 'Assiniboine River', 'Red River', 7],
    [ 'Bahr el Ghazal River', 'Nile River', 20],
    [ 'Baker Lake/Chesterfield Inlet', 'Hudson Bay', 11.5],
    [ 'Baltic Sea', 'Atlantic Ocean', 66],
    [ 'Bay of Bengal', 'Indian Ocean', 62.6],
    [ 'Beaufort Sea', 'Arctic Ocean', 69.7],
    [ 'Beni River', 'Madeira River', 9.2597],
    [ 'Benue River', 'Niger River', 12.9358],
    [ 'Bering Sea', 'Arctic Ocean', 22.3],
    [ 'Bering Sea', 'Pacific Ocean', 22.3],
    [ 'Black Sea', 'Mediterranean Sea', 93],
    [ 'Blue Nile', 'Nile River', 12.5],
    [ 'Brahmaputra River', 'Padma River', 25.1482],
    [ 'Branco River', 'Rio Negro', 7.333],
    [ 'Burdekin River', 'Pacific Ocean', 5.01],
    [ 'Caribbean Sea', 'Atlantic Ocean', 120],
    [ 'Chenab River', 'Panjnad River', 6.8],
    [ 'Chesapeake Bay', 'Atlantic Ocean', 6.4299],
    [ 'Churchill River', 'Hudson Bay', 10.86],
    [ 'Colorado River (Argentina)', 'Atlantic Ocean', 14.4349],
    [ 'Colorado River', 'Gulf of California', 24.6],
    [ 'Columbia River', 'Pacific Ocean', 25.92],
    [ 'Congo River', 'Atlantic Ocean', 144.0501],
    [ 'Danube River', 'Black Sea', 30.7204],
    [ 'Desaguadero River', 'Colorado River', 10],
    [ 'Dnieper River', 'Black Sea', 19.755],
    [ 'Don River', 'Black Sea', 17.1325],
    [ 'Dongting Lake', 'Yangtze River', 9.9],
    [ 'Elbe', 'North Sea', 5.7247],
    [ 'Euphrates', 'Shatt al-Arab', 20.55],
    [ 'Fraser River', 'Pacific Ocean', 9],
    [ 'Ganges River', 'Padma River', 39.2328],
    [ 'Godavari River', 'Indian Ocean', 12.1556],
    [ 'Great Lakes', 'St. Lawrence River', 30.8926],
    [ 'Great Slave Lake', 'Mackenzie River', 37.69],
    [ 'Guaporé River', 'Mamoré River', 13.9203],
    [ 'Gulf of California', 'Pacific Ocean', 24.6],
    [ 'Gulf of Mexico', 'Atlantic Ocean', 120],
    [ 'Gulf of Saint Lawrence', 'Atlantic Ocean', 51.9],
    [ 'Gulf of Tonkin', 'South China Sea', 6.5],
    [ 'Hai River', 'Pacific Ocean', 12.29],
    [ 'Han River', 'Yangtze River', 6.73],
    [ 'Huai River', 'Yangtze River', 6.7],
    [ 'Hudson Bay', 'Atlantic Ocean', 149.09],
    [ 'Hulun Lake', 'Amur River', 6.1906],
    [ 'Indigirka River', 'Arctic Ocean', 13.92],
    [ 'Indus River', 'Arabian Sea', 41.7654],
    [ 'Irrawaddy River', 'Indian Ocean', 15.973],
    [ 'Irtysh River', 'Ob River', 64.613],
    [ 'Ishim River', 'Irtysh River', 7.3],
    [ 'Japurá/Caquetá River', 'Amazon River', 9.87],
    [ 'Jialing River', 'Yangtze River', 6.2],
    [ 'Jubba River', 'Indian Ocean', 19.2134],
    [ 'Jubba-Shebelle basin', 'Indian Ocean', 31.09],
    [ 'Juruá River', 'Amazon River', 8.7193],
    [ 'Kafue River', 'Zambezi River', 6.0157],
    [ 'Kansas River', 'Missouri River', 6.0114],
    [ 'Kasai River', 'Congo River', 35.7211],
    [ 'Khatanga River', 'Arctic Ocean', 14.1],
    [ 'Kolyma River', 'Arctic Ocean', 26.2524],
    [ 'Kotuy River', 'Khatanga River', 6.8],
    [ 'Krishna River', 'Indian Ocean', 9.998],
    [ 'Kwango River', 'Kasai River', 10.17],
    [ 'Lake Athabasca-Rivière des Rochers', 'Slave River', 10.6],
    [ 'Lake Baikal', 'Angara River', 22],
    [ 'Lake Tanganyika', 'Lukuga River', 9.12],
    [ 'Lake Victoria', 'Nile River', 9.22],
    [ 'Lake Winnipeg', 'Nelson River', 37.95],
    [ 'Lena River', 'Arctic Ocean', 89.0638],
    [ 'Liao River', 'Pacific Ocean', 8.97],
    [ 'Liard River', 'Mackenzie River', 10.7],
    [ 'Limpopo River', 'Indian Ocean', 16.2596],
    [ 'Lower Tunguska River', 'Yenisei River', 18.3],
    [ 'Luangwa River', 'Zambezi River', 6.1628],
    [ 'Lukuga River', 'Congo River', 10.46],
    [ 'Luvua River', 'Congo River', 10.24],
    [ 'Mackenzie River', 'Beaufort Sea', 69.7],
    [ 'Madeira River', 'Amazon River', 57.3446],
    [ 'Magdalena River', 'Atlantic Ocean', 9.9397],
    [ 'Mamoré River', 'Madeira River', 24.3567],
    [ 'Marañón River', 'Amazon River', 14.0266],
    [ 'Maya River', 'Aldan River', 6.6],
    [ 'Mbomou River', 'Ubangi River', 6.06],
    [ 'Mediterranean Sea', 'Atlantic Ocean', 330],
    [ 'Mekong River', 'Pacific Ocean', 31.1045],
    [ 'Mississippi River', 'Gulf of Mexico', 123.6371],
    [ 'Missouri River', 'Mississippi River', 51.421],
    [ 'Molopo River', 'Orange River', 14.1777],
    [ 'Murray-Darling basin', 'Southern Ocean', 40.5452],
    [ 'Nelson River', 'Hudson Bay', 41.4],
    [ 'Neman River', 'Baltic Sea', 3.7786],
    [ 'Nen River', 'Songhua River', 9.73],
    [ 'Neva River', 'Baltic Sea', 10.8],
    [ 'Niger River', 'Atlantic Ocean', 87.3263],
    [ 'Nile River', 'Mediterranean Sea', 125.6706],
    [ 'North Sea', 'Atlantic Ocean', 33],
    [ 'Northern Dvina', 'White Sea', 13.7867],
    [ 'Ob River', 'Arctic Ocean', 115.1547],
    [ 'Ogooué River', 'Atlantic Ocean', 8.6431],
    [ 'Ohio River', 'Mississippi River', 18.9423],
    [ 'Olenyok River', 'Arctic Ocean', 8.5],
    [ 'Olyokma River', 'Lena River', 8.1],
    [ 'Orange River', 'Atlantic Ocean', 36.3458],
    [ 'Orinoco River', 'Caribbean Sea', 36.8216],
    [ 'Padma River', 'Bay of Bengal', 62.6],
    [ 'Panjnad River', 'Indus River', 12],
    [ 'Paraguay River', 'Paraná River', 42.3],
    [ 'Paraná River', 'Río de la Plata', 99.7188],
    [ 'Parnaíba River', 'Atlantic Ocean', 12.8048],
    [ 'Peace River', 'Slave River', 11.8],
    [ 'Pearl River', 'Pacific Ocean', 17.52],
    [ 'Pechora River', 'Arctic Ocean', 12.4],
    [ 'Persian Gulf', 'Indian Ocean', 54],
    [ 'Platte River', 'Missouri River', 8.491],
    [ 'Purus River', 'Amazon River', 13.5941],
    [ 'Red River of the North', 'Lake Winnipeg', 11.1],
    [ 'Red River of the South', 'Mississippi River', 6.559],
    [ 'Red River', 'Gulf of Tonkin', 6.5],
    [ 'Red Sea', 'Indian Ocean', 24],
    [ 'Rhine Delta', 'North Sea', 7.15],
    [ 'Rhine Delta', 'North Sea', 9.3],
    [ 'Río de la Plata', 'Atlantic Ocean', 122],
    [ 'Rio Grande', 'Gulf of Mexico', 23.4725],
    [ 'Rio Negro', 'Amazon River', 27.8038],
    [ 'Rufiji River', 'Indian Ocean', 7.894],
    [ 'Ruvuma River', 'Indian Ocean', 6],
    [ 'Salado River (Argentina)', 'Paraná River', 4.7954],
    [ 'Salado River (Buenos Aires)', 'Atlantic Ocean', 6.6],
    [ 'Salween River', 'Indian Ocean', 10.4977],
    [ 'Sangha River', 'Congo River', 9.025],
    [ 'São Francisco River', 'Atlantic Ocean', 23.8539],
    [ 'Saskatchewan River', 'Lake Winnipeg', 12.97],
    [ 'Selenga River', 'Lake Baikal', 17.191],
    [ 'Senegal River', 'Atlantic Ocean', 16.1999],
    [ 'Shatt al-Arab', 'Persian Gulf', 35.37],
    [ 'Shebelle River', 'Jubba River', 12.9972],
    [ 'Shilka River', 'Amur River', 8],
    [ 'Slave River', 'Great Slave Lake', 23.8],
    [ 'Snake River', 'Columbia River', 10.751],
    [ 'Sobat River', 'Nile River', 8.7],
    [ 'Songhua River', 'Amur River', 21.4123],
    [ 'South China Sea', 'Pacific Ocean', 10.3127],
    [ 'St. Lawrence River', 'Atlantic Ocean', 40.5267],
    [ 'St. Lawrence River', 'Gulf of Saint Lawrence', 51.9],
    [ 'Stony Tunguska River', 'Yenisei River', 9.3],
    [ 'Tapajós River', 'Amazon River', 17.51],
    [ 'Taz Estuary', 'Arctic Ocean', 10.1],
    [ 'Tigris River', 'Shatt al-Arab', 8.55],
    [ 'Tisza River', 'Danube River', 6.069],
    [ 'Tobol River', 'Irtysh River', 16.4],
    [ 'Tocantins River', 'Atlantic Ocean', 29.5064],
    [ 'Tshuapa/Ruki River', 'Congo River', 6.71],
    [ 'Ubangi River', 'Congo River', 29.144],
    [ 'Ucayali River', 'Amazon River', 13.0317],
    [ 'Uele River', 'Ubangi River', 5.091],
    [ 'Uruguay River', 'Río de la Plata', 14.1],
    [ 'Ussuri River', 'Amur River', 7.5],
    [ 'Uyandina River', 'Indigirka River', 6.8],
    [ 'Vaal River', 'Orange River', 7.5845],
    [ 'Vilyuy River', 'Lena River', 17.5],
    [ 'Vistula River', 'Baltic Sea', 7.5068],
    [ 'Vitim River', 'Lena River', 8.7],
    [ 'Volta River', 'Atlantic Ocean', 15.7179],
    [ 'White Sea', 'Arctic Ocean', 13.7867],
    [ 'Xi River', 'Pearl River', 13.63],
    [ 'Xingu River', 'Amazon River', 20.0886],
    [ 'Yamuna River', 'Ganges River', 14.1399],
    [ 'Yana River', 'Arctic Ocean', 9.2],
    [ 'Yangtze River', 'Pacific Ocean', 66.4942],
    [ 'Yellow River', 'Pacific Ocean', 32.1329],
    [ 'Yellowstone River', 'Missouri River', 7],
    [ 'Yenisei River', 'Arctic Ocean', 98.6255],
    [ 'Yukon River', 'Bering Sea', 32.4],
    [ 'Zambezi River', 'Indian Ocean', 51.451],
    [ 'Zeya River', 'Amur River', 9]
    // [ 'Amu Darya', 'Aral Sea', 20.6464],
    // [ 'Aras River', 'Kura River', 4.0458],
    // [ 'Athabasca River', 'Lake Athabasca', 3.68],
    // [ 'Awash River', 'Lake Abbe', 4.2],
    // [ 'Bahr Aouk River', 'Chari River', 3.9991],
    // [ 'Barito River', 'Java Sea', 3.9],
    // [ 'Belaya River', 'Kama River', 5.5],
    // [ 'Chao Phraya River', 'Gulf of Thailand', 6.19],
    // [ 'Chari River', 'Lake Chad', 21.1872],
    // [ 'Flinders River', 'Gulf of Carpentaria', 4.2],
    // [ 'Helmand River', 'Sistan Basin', 6.4],
    // [ 'Ili River', 'Lake Balkhash', 5.4],
    // [ 'Juruena River', 'Tapajos River', 7.376],
    // [ 'Kama River', 'Volga River', 19.6],
    // [ 'Koksoak River', 'Ungava Bay', 5.15],
    // [ 'Komadugu-Yobe River', 'Lake Chad', 7.066],
    // [ 'Kura River', 'Caspian Sea', 7.66],
    // [ 'La Grande River', 'James Bay', 3.77],
    // [ 'Logone River', 'Chari River', 3.9182],
    // [ 'Oka River', 'Volga River', 9.5],
    // [ 'Panj River', 'Amu Darya River', 4.4],
    // [ 'Prypiat River', 'Dnieper', 4.704],
    // [ 'Pyasina River', 'Pyasina Gulf', 7],
    // [ 'Ruo Shui', 'Endorheic basin', 5.8922],
    // [ 'Sacramento–San Joaquin River Delta', 'San Francisco Bay', 5.9],
    // [ 'Syr Darya', 'Aral Sea', 30.217],
    // [ 'Taymyr River', 'Kara Sea', 4.8],
    // [ 'Teles Pires River', 'Tapajos River', 5.468],
    // [ 'Thelon River', 'Baker Lake', 5.5],
    // [ 'Ural River', 'Caspian Sea', 8.9],
    // [ 'Volga River', 'Caspian Sea', 54.4771],
    // [ 'Vyatka River', 'Kama River', 5],
    // [ 'Xiang River', 'Lake Dongting', 3.72],
    //[ 'Albany River', 'Hudson Bay', 5.22],
    //[ 'Anabar River', 'Arctic Ocean', 3.9],
    //[ 'Anyuy River (Sakha)', 'Kolyma River', 4.1],
    //[ 'Aripuanã River', 'Madeira River', 5.032],
    //[ 'Aruwimi River', 'Congo River', 4.7434],
    //[ 'Atbarah River', 'Nile River', 5.8],
    //[ 'Back River', 'Arctic Ocean', 4.11],
    //[ 'Balsas River', 'Pacific Ocean', 4.337],
    //[ 'Bandama River', 'Atlantic Ocean', 3.8],
    //[ 'Bani River', 'Niger River', 5.659],
    //[ 'Bermejo River', 'Paraguay River', 4.1284],
    //[ 'Brazos River', 'Gulf of Mexico', 4.5],
    //[ 'Canadian River', 'Arkansas River', 4.7576],
    //[ 'Chambal River', 'Yamuna River', 5.5297],
    //[ 'Chindwin River', 'Irrawaddy River', 3.9685],
    //[ 'Chulym River', 'Ob River', 5.2],
    //[ 'Colorado River (Texas)', 'Gulf of Mexico', 3.99],
    //[ 'Cuanza River', 'Atlantic Ocean', 5.7795],
    //[ 'Cunene River', 'Atlantic Ocean', 4.114],
    //[ 'Donets', 'Don River', 3.82],
    //[ 'Douro / Duero', 'Atlantic Ocean', 3.7646],
    //[ 'Essequibo River', 'Atlantic Ocean', 5.9532],
    //[ 'Fitzroy River (Queensland)', 'Pacific Ocean', 5.5083],
    //[ 'Ghaghara / Karnali River', 'Ganges River', 4.94],
    //[ 'Green River', 'Colorado River', 4.81],
    //[ 'Grijalva-Usumacinta basin', 'Gulf of Mexico', 5.19],
    //[ 'Guaviare River', 'Orinoco River', 5.3455],
    //[ 'Hayes River', 'Hudson Bay', 4.2],
    //[ 'Iriri River', 'Xingu River', 5.4728],
    //[ 'Kapuas River', 'South China Sea', 3.8127],
    //[ 'Kheta River', 'Khatanga River', 3.9],
    //[ 'Kuskokwim River', 'Bering Sea', 4.8],
    //[ 'Kwando/Chobe River', 'Zambezi River', 4.3781],
    //[ 'Loire', 'Atlantic Ocean', 4.5],
    //[ 'Lomami River', 'Congo River', 4.4869],
    //[ 'Lukenie River', 'Congo River', 5.1518],
    //[ 'Madre de Dios River', 'Beni River', 4.8374],
    //[ 'Mahanadi River', 'Indian Ocean', 5.47],
    //[ 'Malagarasi River', 'Lake Tanganyika', 5],
    //[ 'Markha River', 'Vilyuy River', 3.86],
    //[ 'Min River (Sichuan)', 'Yangtze River', 5.4],
    //[ 'Mobile River', 'Gulf of Mexico', 4.4],
    //[ 'Moose River (Ontario)', 'Hudson Bay', 4.19],
    //[ 'Mun River', 'Mekong River', 4.602],
    //[ 'Napo River', 'Amazon River', 3.946],
    //[ 'Narmada River', 'Arabian Sea', 3.81],
    //[ 'North Saskatchewan River', 'Saskatchewan River', 4.74],
    //[ 'Northern Sosva River', 'Ob River', 3.8],
    //[ 'Oder', 'Baltic Sea', 4.5892],
    //[ 'Omolon River', 'Kolyma River', 4.4],
    //[ 'Orkhon River', 'Selenga River', 5.1288],
    //[ 'Ottawa River', 'St. Lawrence River', 5.65],
    //[ 'Pecos River', 'Rio Grande', 4.4],
    //[ 'Penobscot River', 'Atlantic Ocean', 0.86],
    //[ 'Pilcomayo River', 'Paraguay River', 4.4171],
    //[ 'Porcupine River', 'Yukon River', 4.55],
    //[ 'Pranhita River', 'Godavari River', 4.2115],
    //[ 'Pur River', 'Taz Estuary', 4.3],
    //[ 'Putumayo River', 'Amazon River', 5.7],
    //[ 'Rhone River', 'Mediterranean Sea', 3.8053],
    //[ 'Rio Grande (Paraná River)', 'Paraná River', 5.5],
    //[ 'Río Negro (Argentina)', 'Atlantic Ocean', 3.9],
    //[ 'Sanaga River', 'Atlantic Ocean', 5.4],
    //[ 'Sankuru River', 'Kasai River', 5.8345],
    //[ 'Santiago-Lerma basin', 'Pacific Ocean', 5.2752],
    //[ 'Sava River', 'Danube River', 3.6841],
    //[ 'Save River', 'Indian Ocean', 4.109],
    //[ 'Severn River (northern Ontario)', 'Hudson Bay', 3.97],
    //[ 'Shire River (Lake Malawi)', 'Zambezi River', 5.7591],
    //[ 'South Saskatchewan River', 'Saskatchewan River', 5.64],
    //[ 'Sutlej River', 'Indus River', 4.4148],
    //[ 'Tambo-Ene-Apurímac River', 'Ucayali River', 5.076],
    //[ 'Tana River (Kenya)', 'Indian Ocean', 4.8659],
    //[ 'Tanana River', 'Yukon River', 4.4],
    //[ 'Taseyeva River', 'Angara River', 4.9],
    //[ 'Taz River', 'Taz Estuary', 5.8],
    //[ 'Tennessee River', 'Ohio River', 4.0876],
    //[ 'Tietê River', 'Paraná River', 5.8],
    //[ 'Trombetas River', 'Amazon River', 4.9283],
    //[ 'Uchur River', 'Aldan River', 4.4],
    //[ 'Vychegda River', 'Northern Dvina', 4.7],
    //[ 'Wabash River', 'Ohio River', 4],
    //[ 'Wei River', 'Yellow River', 5.2],
    //[ 'Winnipeg River', 'Lake Winnipeg', 5.24],
    //[ 'Yalong River', 'Yangtze River', 4.9593],

  ]);

//  Sets chart options.
  var options = {
    // width: 1200,
    // height: 500,
    sankey: {
      node: {
        label: {
      fontName: 'Lato',
      fontSize: 10,
      slantedText:true,
      slantedTextAngle:90,
      // roatation: 90,
      color: 'white',
    },
        // interactivity: true, // Allows you to select nodes.
        labelPadding: 5,     // Horizontal distance between the label and the node.
        nodePadding: 2,     // Vertical distance between nodes.
        width: 25,            // Thickness of the node.
        }
},
  };

  // Instantiates and draws our chart, passing in some options.
  var chart = new google.visualization.Sankey(document.getElementById('sankey_multiple'));
  chart.draw(data, options);
}
